{"start":"2024-12-05T22:02:41.860892","end":"2024-12-05T22:02:41.860892","exit_code":-1,"error_msg":"an unhandled error occurred: python inline source runtime error: module 'pulumi_gcp.compute' has no attribute 'InstanceBootDiskArgs'\nTraceback (most recent call last):\n  File \"/venv/inspector/lib/python3.12/site-packages/pulumi/automation/_server.py\", line 80, in run\n    loop.run_until_complete(run_in_stack(self.program))\n  File \"/usr/local/lib/python3.12/asyncio/base_events.py\", line 687, in run_until_complete\n    return future.result()\n           ^^^^^^^^^^^^^^^\n  File \"/venv/inspector/lib/python3.12/site-packages/pulumi/runtime/stack.py\", line 145, in run_in_stack\n    await run_pulumi_func(run)\n  File \"/venv/inspector/lib/python3.12/site-packages/pulumi/runtime/stack.py\", line 55, in run_pulumi_func\n    func()\n  File \"/venv/inspector/lib/python3.12/site-packages/pulumi/runtime/stack.py\", line 142, in run\n    Stack(func)\n  File \"/venv/inspector/lib/python3.12/site-packages/pulumi/runtime/stack.py\", line 171, in __init__\n    awaitable = func()\n                ^^^^^^\n  File \"/venv/inspector/lib/python3.12/site-packages/sc_runner/runner.py\", line 79, in pulumi_program\n    return resource_f(**resource_opts)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/venv/inspector/lib/python3.12/site-packages/sc_runner/resources/gcp.py\", line 54, in resources_gcp\n    boot_disk=gcp.compute.InstanceBootDiskArgs(\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: module 'pulumi_gcp.compute' has no attribute 'InstanceBootDiskArgs'\n\n","task_hash":"e39ab2357d279f3dca9c9e68a34364b179167974","version":null,"stdout_bytes":null,"stderr_bytes":null,"outputs":[]}